#!/bin/bash

# Determine toolpath if not set already
relativepath="./" # Define relative path to go from this script to the root level of the tool
if [[ ! -v toolpath ]]; then scriptpath=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd ); toolpath=$(realpath --canonicalize-missing ${scriptpath}/${relativepath}); fi

# Load Default Settings
source "${toolpath}/config.default.sh"

##################################################
############## CONVERSION OPTIONS ################
##################################################

# Program to copy Blocks (dd or ddrescue)
PROGRAM_COPY_BLOCKS="ddrescue"


##################################################
############### BENCHMARK OPTIONS ################
##################################################

# Debug Mode
BENCHMARK_DEBUG_ENABLE=0

# Test Device
# UUID generated by `uuidgen` was "7799c748-a789-4f99-ba01-d144b0846f20"
BENCHMARK_VM_TEST_DEVICE="/dev/disk/by-id/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

# Test Path
BENCHMARK_VM_TEST_PATH="/mnt/test"

# Guest ID
BENCHMARK_VM_ID="XXX"

# Guest Virtual Disk
BENCHMARK_VM_VIRTUAL_DISK="rpool/data/vm-XXX-disk-Y"

# Default Size to write to Disk for the entire Test
BENCHMARK_VM_DEFAULT_SIZE="1G"

# Host Devices to be Analyzed (clear default Settings)
unset BENCHMARK_HOST_DEVICES
BENCHMARK_HOST_DEVICES=()
BENCHMARK_HOST_DEVICES+=("/dev/disk/by-id/ata-XXX")
BENCHMARK_HOST_DEVICES+=("/dev/disk/by-id/ata-YYY")
BENCHMARK_HOST_DEVICES+=("/dev/mapper/ata-XXX_crypt")
BENCHMARK_HOST_DEVICES+=("/dev/mapper/ata-YYY_crypt")
